# Generated by Django 5.2 on 2026-06-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("RECEPTION", "Reception"),
                    ("DOCTOR", "Doctor"),
                    ("PATIENT", "Patient"),
                ],
                max_length=20,
            ),
        ),
    ]
