# Generated by Django 5.2 on 2026-06-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_rename_doctors_appointment_doctor_and_more"),
        ("doctors", "0003_doctor_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="doctors.doctor",
            ),
        ),
    ]
