# Generated by Django 5.2 on 2026-06-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_alter_appointment_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
