# Generated by Django 5.2 on 2026-06-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_doctor_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("Cardiology", "Cardiology"),
                    ("Neurology", "Neurology"),
                    ("Orthopedics", "Orthopedics"),
                    ("Dermatology", "Dermatology"),
                    ("Pediatrics", "Pediatrics"),
                ],
                max_length=50,
            ),
        ),
    ]
