# Generated by Django 5.2 on 2026-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0004_alter_doctor_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("Cardiology", "Cardiology"),
                    ("Neurology", "Neurology"),
                    ("Orthopedics", "Orthopedics"),
                    ("Dermatology", "Dermatology"),
                    ("Pediatrics", "Pediatrics"),
                    ("Gynecology", "Gynecology"),
                    ("Psychiatry", "Psychiatry"),
                    ("Oncology", "Oncology"),
                    ("Radiology", "Radiology"),
                    ("General Medicine", "General Medicine"),
                    ("ENT", "ENT"),
                    ("Ophthalmology", "Ophthalmology"),
                    ("Urology", "Urology"),
                    ("Gastroenterology", "Gastroenterology"),
                    ("Pulmonology", "Pulmonology"),
                    ("Nephrology", "Nephrology"),
                    ("Endocrinology", "Endocrinology"),
                    ("Anesthesiology", "Anesthesiology"),
                    ("Emergency Medicine", "Emergency Medicine"),
                    ("Physiotherapy", "Physiotherapy"),
                ],
                max_length=50,
            ),
        ),
    ]
